notifications:
  slack: knot3:bsZjAIfIGf9T5WqUdCUcUsgh
  email:
    recipients:
    - pascal.knodel@student.kit.edu
    - tobias.schulz186@gmail.com
    - daniel.warzel@student.kit.edu
    - gerd.augsburg@student.kit.edu
    - uahih@student.kit.edu
    on_success: change
    on_failure: always
language: c
script:
- git config --global user.name "Knot3 Server"
- git config --global user.email "uaeti@student.kit.edu"
- git remote set-url origin https://github.com/${TRAVIS_REPO_SLUG}.git
- git fetch --unshallow
- git checkout -f ${TRAVIS_BRANCH}
- git checkout -f HEAD
- scripts/package.sh
- scripts/deploy.sh
- git submodule update --init --recursive
- make dep-ubuntu-precise
- make test
env:
  global:
  - secure: W7sO9sslOwT3l4TzJ/slpKEOLlbu1usYiMJa7oESZEg/nHIa8IK0hsWrnQ5LgIfTRq/kz/N2UuX3nJGOY+fpBYTjJMbOEifXiqnzCXlvHy376pYcm8ijwCjb02qdeaDtOrategSARnRp5fmfBkrPVgjyXs3g6jbR+ir+SBTCLCw=
  - secure: sYpWn1SS7utHdhH4gEsjSbnkzExZdc+jV2V1lkzdQmWPZhX3qdtci+8Du7dpZ8paYKaN7nHSpr26yPxOH/gRtPyqGfnRlj5DWsVzCigP07PTStvoNN//4H8cTAx5ULUVJLJ0Si7XELbOdQrjwJWkQmVjgQdGISCW/dWSNd1S/G0=
