notifications:
  email:
    recipients:
      - pascal.knodel@student.kit.edu
      - tobias.schulz186@gmail.com
      - daniel.warzel@student.kit.edu
      - gerd.augsburg@student.kit.edu
      - uahih@student.kit.edu
    on_success: change
    on_failure: always
language: c
script:
  - make dep-ubuntu-precise
  - make test
