notifications:
  slack: knot3:bsZjAIfIGf9T5WqUdCUcUsgh
  email:
    recipients:
      - pascal.knodel@student.kit.edu
      - tobias.schulz186@gmail.com
      - daniel.warzel@student.kit.edu
      - gerd.augsburg@student.kit.edu
      - uahih@student.kit.edu
    on_success: change
    on_failure: always
language: c
script:
  - git submodule update --init --recursive
  - make dep-ubuntu-precise
  - make test
