notifications:
  email:
    recipients:
      - pascal.knodel@student.kit.edu
      - tobias.schulz186@gmail.com
      - daniel.warzel@student.kit.edu
      - gerd.augsburg@student.kit.edu
      - uahih@student.kit.edu
    on_success: change
    on_failure: always
language: c
install:
  - sudo apt-get install mono-devel mono-dmcs nunit-console libopenal1 libsdl2-2.0-0 libsdl2-mixer-2.0-0 libsdl2-image-2.0-0
before_install:
  - wget https://github.com/pse-knot/MonoGame/releases/download/v3.1.2/MonoGame-Linux-20130126.zip
  - mkdir -p src/bin/Debug/
  - unzip -d src/bin/Debug/ MonoGame-Linux-20130126.zip
  - mkdir -p tests/bin/Debug/
  - unzip -d tests/bin/Debug/ MonoGame-Linux-20130126.zip
script:
  - make test
